name: home_page
description: Personal Web Page

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.1
flutter:
  assets:
    - gcHadoop.png
    - weatherAppScaled.png
    - antialiasedPot.png
